name: Send Telegram Proxies

on:
  # این اکشن را هر 3 ساعت یک بار به صورت خودکار اجرا می‌کند
  schedule:
    - cron: '0 */3 * * *'
  
  # این گزینه به شما اجازه می‌دهد اکشن را به صورت دستی هم اجرا کنید
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # مرحله ۱: کد شما را از مخزن دریافت می‌کند
      - name: Checkout repository
        uses: actions/checkout@v4

      # مرحله ۲: پایتون را نصب و آماده‌سازی می‌کند
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # مرحله ۳: کتابخانه‌های مورد نیاز را از فایل requirements.txt نصب می‌کند
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # مرحله ۴: اسکریپت پایتون را اجرا می‌کند
      - name: Run Python script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }} # سکرت توکن را به اسکریپت می‌دهد
        run: python Bot.py
